# Generated by Django 5.0.2 on 2024-03-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwords',
        ),
    ]
