# Generated by Django 5.0.2 on 2024-03-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_rename_password_user_passwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwords',
            new_name='password',
        ),
    ]
