# Generated by Django 5.0 on 2023-12-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0004_alter_cart_product_id_alter_cart_user_id'),
        ('admin_ultras', '0030_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.product')),
            ],
        ),
    ]
