# Generated by Django 5.0 on 2023-12-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0005_wishlist'),
        ('admin_ultras', '0032_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.product', unique=True),
        ),
    ]
