# Generated by Django 5.0 on 2023-12-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0006_alter_wishlist_wishlist'),
        ('admin_ultras', '0032_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.product'),
        ),
    ]
