# Generated by Django 5.0 on 2023-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0007_wishlist_user_id_alter_wishlist_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
