# Generated by Django 5.0 on 2023-12-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0008_alter_wishlist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
