# Generated by Django 5.0 on 2023-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0009_remove_cart_amount_remove_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
