# Generated by Django 5.0 on 2023-12-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0012_alter_wishlist_user_id'),
        ('admin_ultras', '0033_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.profile'),
        ),
    ]
