# Generated by Django 5.0 on 2023-12-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0013_alter_wishlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
