# Generated by Django 5.0 on 2023-12-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0014_rename_address_user_city_user_address1_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
