# Generated by Django 5.0 on 2024-01-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UltrasApp', '0015_alter_user_pincode'),
        ('admin_ultras', '0033_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UltrasApp.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UltrasApp.user')),
            ],
        ),
    ]
