# Generated by Django 5.0 on 2023-12-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
