# Generated by Django 5.0 on 2023-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
