# Generated by Django 5.0 on 2023-12-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0005_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
