# Generated by Django 5.0 on 2023-12-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0007_alter_profile_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
