# Generated by Django 5.0 on 2023-12-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
