# Generated by Django 5.0 on 2023-12-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
