# Generated by Django 5.0 on 2023-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_ultras', '0013_delete_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=6)),
                ('bdate', models.CharField(default='', max_length=10)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('skills', models.CharField(default='', max_length=100)),
                ('image', models.FileField(default='', upload_to='media/')),
            ],
        ),
    ]
