# Generated by Django 5.0 on 2023-12-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0015_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
