# Generated by Django 5.0 on 2023-12-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0017_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
