# Generated by Django 5.0 on 2023-12-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0022_categoryo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryO',
        ),
    ]
