# Generated by Django 5.0 on 2023-12-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0025_brand_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('material', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('images', models.FileField(default='', upload_to='media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ultras.tag')),
            ],
        ),
    ]
