# Generated by Django 5.0 on 2023-12-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ultras', '0029_user_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
